In [ ]:
# Ruchika Bhat  25070123095
# Aim: Study of Numpy Library

In [33]:
# declaration of numpy
# (we can print matrices,can find which type of matric it is, dimensions using numpy library)
import numpy as np

a = np.array([1,10,20,30,40,50,500])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

# dimension of array
print(a.ndim)
print(b.ndim)

# gives no.of rows and columns
print(a.shape)
print(b.shape)

# gives datatype
#  (if we change an integer number in a matrix into decimal then it will give its datatype as float)
print(a.dtype)
print(b.dtype)

# in-built functions using numpy
print(np.zeros((2,3)))              # generates a zero matrix

print(np.ones((3,3)))               # generates a one matrix

print(np.eye(3))                    # generates an identity matrix

print(np.arange(1,10,2))            # starting range:1, stop at 10-1,and with a gap of 2

print(np.linspace(0,1,4))           # generates equally spaced matrix having 4 elements from 0 to 1

print(a + 5)                        # adds 5 to every element

print(b * 2)                        # multiplies every element by 2

print(np.mean(a))                   # calculate the mean of matrix

print(np.median(a))                 # calculate the median of matrix

print(np.max(a))                    # calculate the maximum of matrix

print(np.min(a))                    # calculate the minimum of matrix

print(np.sum(a))                    # calculate the sum

print(np.std(a))                    # calculate the standard deviation

[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]
1
2
(7,)
(2, 3)
int64
int64
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 3 5 7 9]
[0.         0.33333333 0.66666667 1.        ]
[  6  15  25  35  45  55 505]
[[ 2  4  6]
 [ 8 10 12]]
93.0
30.0
500
1
651
166.88661677061722
